// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios; // macOS는 iOS 설정을 공유
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_W28LZMPbuwTHaYa_dc1j_1bEt0PXOXw',
    appId: '1:1047247760638:web:4a60bd78ad35b7b2b349af',
    messagingSenderId: '1047247760638',
    projectId: 'flutter-todolist-dev',
    authDomain: 'flutter-todolist-dev.firebaseapp.com',
    storageBucket: 'flutter-todolist-dev.firebasestorage.app',
    measurementId: 'G-YFNPGHXNHH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZiszcvhi7yKG2ZeiVIU-A4OuXYhqiXMU',
    appId: '1:1047247760638:android:b45b6f2f2f3a9d95b349af',
    messagingSenderId: '1047247760638',
    projectId: 'flutter-todolist-dev',
    storageBucket: 'flutter-todolist-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP65uOVauVUOrJ50TBNxiJYJ8N1c8v32E',
    appId: '1:1047247760638:ios:1b8d1c01d6f29a26b349af',
    messagingSenderId: '1047247760638',
    projectId: 'flutter-todolist-dev',
    storageBucket: 'flutter-todolist-dev.firebasestorage.app',
    iosBundleId: 'com.example.flutterTodolistDev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_W28LZMPbuwTHaYa_dc1j_1bEt0PXOXw',
    appId: '1:1047247760638:web:7e047eeaa6676d6bb349af',
    messagingSenderId: '1047247760638',
    projectId: 'flutter-todolist-dev',
    authDomain: 'flutter-todolist-dev.firebaseapp.com',
    storageBucket: 'flutter-todolist-dev.firebasestorage.app',
    measurementId: 'G-YDXN3L107M',
  );
}
